version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t httpd-kasaiso:0 .
      - docker push httpd-kasaiso:0
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - printf '{"Version":"1.0","ImageURI":"%s"}' 514004723145.dkr.ecr.eu-west-1.amazonaws.com/httpd-kasaiso:0 > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - taskdef.json

